import { addAccordion } from './accordion.js';
import { addAlert } from './alert.js';
import { addBadge } from './badge.js';
import { addCarousel } from './carousel.js';
import { addForm } from './form.js';
import { addHorizontalForm } from './horizontal-form.js';
import { addPagination } from './pagination.js';
import { addProgress } from './progress.js';
import { addSpinner } from './spinner.js';
import { addTable } from './table.js';
import { addTypography } from './typography.js';
import { addValidation } from './validation.js';

window.addAlert = addAlert;
window.addAccordion = addAccordion;
window.addBadge = addBadge;
window.addCarousel = addCarousel;
window.addForm = addForm;
window.addHorizontalForm = addHorizontalForm;
window.addPagination = addPagination;
window.addProgress = addProgress;
window.addSpinner = addSpinner;
window.addTable = addTable;
window.addTypography = addTypography;
window.addValidation = addValidation;